#!/bin/sh
# $Id: g++.in 5608 2010-01-07 19:51:45Z cher $
# Copyright (c) 2001-2010 Alexander Chernov <cher@ejudge.ru>

# using EJUDGE_FLAGS we may pass additional flags

if false; then
LANG_CONFIG_DIR="/home/judges/compile/conf/lang.d"
[ "${EJUDGE_LANG_CONFIG}" = "" ] && EJUDGE_LANG_CONFIG="${LANG_CONFIG_DIR}/ants++.cfg"

if [ -f "${EJUDGE_LANG_CONFIG}" ]
then
  . "${EJUDGE_LANG_CONFIG}"
else
  version="unknown"
  GPPRUN="g++"
  GPPDIR=
fi

if [ x"${version}" = x ]
then
  echo "This language is not supported." >&2
  exit 1
fi

if [ x"${GPPDIR}" != x ]
then
    PATH="${GPPDIR}:${PATH}"
fi

[ x"${EJUDGE_FLAGS}" = x ] && EJUDGE_FLAGS="-Wall -O2"
fi
unset LANG
unset LC_ALL
unset LC_MESSAGES
unset LANGUAGE
x="$(echo "$2" | sed 's/^0*//')"
if [ "$(head -c 1 $1)" = "{" ]; then
	head -1 $1 > /home/judges/ants/names/names_$x.json
	N=2
else
	N=1
fi

IDS=""
for a in `cat $1 | tail -n +$N`; do
    f="/home/judges/ants/so/`printf %06d $(echo $a | sed 's/^0*//')`/libAnt.so"
    if [ ! -e "$f" ]; then
        echo "Run ID $a is bad!" >&2
        exit 1
    fi
    IDS="$IDS\n$f"
done
#mkdir /home/judges/ants/so/$2
#g++ -O2 -shared -std=c++11 -I/home/judges/ants/include -o /home/judges/ants/so/$2/libAnt.so $1a
if [ -z "$ANTSTT_MAP" ]; then
	ANTSTT_MAP=00
fi

if [ -z "$ANTSTT_STEPS" ]; then
	ANTSTT_STEPS=1000
fi

cat > $2 <<EOF
#!/bin/bash
echo -e "/home/judges/ants/maps/$ANTSTT_MAP\n$ANTSTT_STEPS\n500\n$IDS" | /home/judges/ants/bin/Ants $ANTSTT_ARGS

EOF
chmod +x $2
